# Generated by Django 2.1.1 on 2018-10-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='cv/docs/'),
        ),
    ]
