# Generated by Django 2.1.1 on 2018-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20180928_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Kalamata Capital Group LLC', max_length=200),
            preserve_default=False,
        ),
    ]
