# Generated by Django 2.1.1 on 2018-10-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_skilltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_type',
        ),
        migrations.AddField(
            model_name='skill',
            name='stype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cv.SkillType'),
        ),
    ]
