# Generated by Django 2.1.1 on 2018-09-30 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('school_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('skill_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cv.Job'),
        ),
    ]
